apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: elasticsearch
    labels:
      app: jaeger
      name: jaeger-elasticsearch-service
      jaeger-infra: elasticsearch-service
  spec:
    ports:
    - port: 9200
      name: elasticsearch
    clusterIP: None
    selector:
      app: elasticsearch
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: elasticsearch
  spec:
    serviceName: elasticsearch
    replicas: 3
    template:
      metadata:
        labels:
          app: elasticsearch
          type: databases
          availability: restricted
          jaeger-infra: elasticsearch-replica
      spec:
        containers:
          - name: elasticsearch
            image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
            command:
              - bin/elasticsearch
            args:
              - "-Ehttp.host=0.0.0.0"
              - "-Etransport.host=127.0.0.1"
            volumeMounts:
              - name: data
                mountPath: /data
        volumes:
          - name: data
            emptyDir: {}
