apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "dvonthenen/jop-backend:latest"
          imagePullPolicy: Always
          env:
            - name: HOST_IP
              value: "myrel-jaeger-agent.kube-system.svc.cluster.local"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LISTEN_IP
              value: "0.0.0.0"
            - name: LISTEN_PORT
              value: "80"
