apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simple-alpine
  labels:
    app: simple-alpine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-alpine
    spec:
      containers:
        - name: simple-alpine
          image: "dvonthenen/simple:v1-alpine"
