apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
  labels:
    k8s-app: grafana
    version: v4.4.1
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        k8s-app: grafana
        version: v4.4.1
    spec:
      containers:
        - name: grafana
          image: "grafana/grafana:4.4.1"
