apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zipkin
  labels:
    k8s-app: zipkin
    version: v1.28.1
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
        k8s-app: zipkin
        version: v1.28.1
    spec:
      containers:
        - name: zipkin
          image: "openzipkin/zipkin:1.28.1"
