apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-ubuntu
  name: simple-ubuntu
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: simple-ubuntu
